package schema

var TableClients = `
    CREATE TABLE IF NOT EXISTS clients (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nom TEXT NOT NULL,
        prenom TEXT NOT NULL,
        date_naissance DATE,
        sexe TEXT,
        lieu_naissance TEXT,
        statut_marital TEXT,
        occupation TEXT,
        employeur TEXT,
        profession TEXT,
        niveau_scolaire TEXT,
        langue_preferee TEXT,
        origine_ethnique TEXT,
        premiere_nation_id INTEGER,           -- L'ID de la table ref_nations
        premiere_nation_communaute TEXT,         -- Le string construit (ex: "Cris | Mistissini")
        premiere_nation TEXT,       -- 0: Non, 1: Inscrit, 2: En cours (ou selon votre logique Table Ref)
        identite_genre TEXT,
        orientation_sexuelle TEXT,
        religion TEXT,
        premiere_langue TEXT,
        telephone TEXT,
        cellulaire TEXT,
        email TEXT,
        adresse TEXT,
        appartement TEXT,
        code_postal TEXT,
        ville TEXT,
        mcode TEXT REFERENCES MUN(mcode),
        arrcod TEXT REFERENCES ARR(arrcod),
        pays TEXT,
        province TEXT,
        numero_assurance_maladie TEXT,
        numero_securite_sociale TEXT,
        no_hcm TEXT,
        no_chaur TEXT,
        no_dossier_leopard TEXT,
        medecin_famille_No_Licence TEXT,
        notaire_id INTEGER,
        pharmacie_id INTEGER,
        pivot_id INTEGER,
        rpa_id INTEGER,
        chsld_id INTEGER,
        ri_id INTEGER,
        procuration_bancaire TEXT,
        procuration_notariee TEXT,
        tutelle_active INTEGER DEFAULT 0,
        tutelle_type TEXT,
        tutelle_bien INTEGER DEFAULT 0,
        tutelle_personne INTEGER DEFAULT 0,
        tutelle_date_debut DATE,
        tutelle_date_renouvellement DATE,
        tuteur_nom TEXT,
        tuteur_prenom TEXT,
        tuteur_telephone TEXT,
        tuteur_cellulaire TEXT,
        tuteur_email TEXT,
        tuteur_adresse TEXT,
        tuteur_code_postal TEXT,
        tuteur_ville TEXT,
        note_fixe TEXT,
        Actif INTEGER DEFAULT 1,
        dcd INTEGER DEFAULT 0,
        date_deces DATE,
        created_by INTEGER,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
`
