package schema

var TableClients = `
    CREATE TABLE IF NOT EXISTS clients (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		nom TEXT NOT NULL,
		prenom TEXT NOT NULL,
		date_naissance DATE,
		sexe TEXT,
		lieu_naissance TEXT,
		statut_marital TEXT,
		occupation TEXT,
		employeur TEXT,
		profession TEXT,
		niveau_scolaire TEXT,
		langue_preferee TEXT,
		origine_ethnique TEXT,
		premiere_nation INTEGER DEFAULT 0,
		identite_genre TEXT,
		orientation_sexuelle TEXT,
		religion TEXT,
		premiere_langue TEXT,
		telephone TEXT,
		cellulaire TEXT,
		email TEXT,
		adresse TEXT,
		appartement TEXT,
		code_postal TEXT,
		ville TEXT,
		pays TEXT,
		province TEXT,
		numero_assurance_maladie TEXT,
		numero_securite_sociale TEXT,
		no_hcm TEXT,
		no_chaur TEXT,
		no_dossier_leopard TEXT,
		medecin_famille_No_Licence TEXT,
		notaire_id INTEGER,
		pivot_id INTEGER,
		rpa_id INTEGER,
		chsld_id INTEGER,
		ri_id INTEGER,
		procuration_bancaire TEXT,
		procuration_notariee TEXT,
		note_fixe TEXT,
		Actif INTEGER DEFAULT 1,
		dcd INTEGER DEFAULT 0,
		date_deces DATE,
		created_by INTEGER,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY(created_by) REFERENCES users(id)
	);
`
