// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function ChangePassword(arg1:models.ChangePasswordRequest):Promise<void>;

export function ClientFolderExists(arg1:string):Promise<boolean>;

export function CreateClient(arg1:models.CreateClientRequest):Promise<number>;

export function CreateClientFolderStructure(arg1:Record<string, any>):Promise<main.ClientFolderResult>;

export function CreateNote(arg1:models.CreateNoteRequest):Promise<number>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function ExportToClientFolder(arg1:Record<string, any>):Promise<main.ClientFolderResult>;

export function GetBasePath():Promise<string>;

export function GetClientByID(arg1:number):Promise<models.Client>;

export function GetClientFolderInfo(arg1:string):Promise<main.ClientFolderInfo>;

export function GetClientNotes(arg1:number):Promise<Array<models.NoteListItem>>;

export function GetClientNotesFiltered(arg1:models.NotesFilter):Promise<Array<models.NoteListItem>>;

export function GetClients():Promise<Array<models.Client>>;

export function GetCurrentUserProfile():Promise<models.User>;

export function GetNoteByID(arg1:number):Promise<models.Note>;

export function GetNotesStats(arg1:number):Promise<Record<string, any>>;

export function GetSettings():Promise<models.UserSettings>;

export function ListClientFolders():Promise<Array<string>>;

export function LockNote(arg1:number):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function OpenClientFolder(arg1:string):Promise<main.ClientFolderResult>;

export function OpenMainClientsFolder():Promise<main.ClientFolderResult>;

export function RenameClientFolder(arg1:string,arg2:string):Promise<main.ClientFolderResult>;

export function UpdateClient(arg1:models.UpdateClientRequest):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;

export function UpdateProfile(arg1:models.UpdateProfileRequest):Promise<void>;

export function UpdateSettings(arg1:models.UpdateSettingsRequest):Promise<void>;
