// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function ClientFolderExists(arg1) {
  return window['go']['main']['App']['ClientFolderExists'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateClientFolderStructure(arg1) {
  return window['go']['main']['App']['CreateClientFolderStructure'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function ExportToClientFolder(arg1) {
  return window['go']['main']['App']['ExportToClientFolder'](arg1);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetClientByID(arg1) {
  return window['go']['main']['App']['GetClientByID'](arg1);
}

export function GetClientFolderInfo(arg1) {
  return window['go']['main']['App']['GetClientFolderInfo'](arg1);
}

export function GetClientNotes(arg1) {
  return window['go']['main']['App']['GetClientNotes'](arg1);
}

export function GetClientNotesFiltered(arg1) {
  return window['go']['main']['App']['GetClientNotesFiltered'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetCurrentUserProfile() {
  return window['go']['main']['App']['GetCurrentUserProfile']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetNotesStats(arg1) {
  return window['go']['main']['App']['GetNotesStats'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListClientFolders() {
  return window['go']['main']['App']['ListClientFolders']();
}

export function LockNote(arg1) {
  return window['go']['main']['App']['LockNote'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenClientFolder(arg1) {
  return window['go']['main']['App']['OpenClientFolder'](arg1);
}

export function OpenMainClientsFolder() {
  return window['go']['main']['App']['OpenMainClientsFolder']();
}

export function RenameClientFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameClientFolder'](arg1, arg2);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
