// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveNotaire(arg1) {
  return window['go']['main']['App']['ArchiveNotaire'](arg1);
}

export function ArchiverOrganisation(arg1) {
  return window['go']['main']['App']['ArchiverOrganisation'](arg1);
}

export function ArchiverService(arg1) {
  return window['go']['main']['App']['ArchiverService'](arg1);
}

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function ClientFolderExists(arg1) {
  return window['go']['main']['App']['ClientFolderExists'](arg1);
}

export function CreateAppel(arg1) {
  return window['go']['main']['App']['CreateAppel'](arg1);
}

export function CreateCHSLD(arg1) {
  return window['go']['main']['App']['CreateCHSLD'](arg1);
}

export function CreateCim11Code(arg1) {
  return window['go']['main']['App']['CreateCim11Code'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateClientFolderStructure(arg1) {
  return window['go']['main']['App']['CreateClientFolderStructure'](arg1);
}

export function CreateContact(arg1) {
  return window['go']['main']['App']['CreateContact'](arg1);
}

export function CreateContrat(arg1) {
  return window['go']['main']['App']['CreateContrat'](arg1);
}

export function CreateDepense(arg1) {
  return window['go']['main']['App']['CreateDepense'](arg1);
}

export function CreateFacture(arg1) {
  return window['go']['main']['App']['CreateFacture'](arg1);
}

export function CreateFirstUser(arg1) {
  return window['go']['main']['App']['CreateFirstUser'](arg1);
}

export function CreateMedecin(arg1) {
  return window['go']['main']['App']['CreateMedecin'](arg1);
}

export function CreateNotaire(arg1) {
  return window['go']['main']['App']['CreateNotaire'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateOrganisation(arg1) {
  return window['go']['main']['App']['CreateOrganisation'](arg1);
}

export function CreatePayeur(arg1) {
  return window['go']['main']['App']['CreatePayeur'](arg1);
}

export function CreatePlan(arg1) {
  return window['go']['main']['App']['CreatePlan'](arg1);
}

export function CreateRefListe(arg1) {
  return window['go']['main']['App']['CreateRefListe'](arg1);
}

export function CreateRevenu(arg1) {
  return window['go']['main']['App']['CreateRevenu'](arg1);
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function CreateSubfolder(arg1, arg2) {
  return window['go']['main']['App']['CreateSubfolder'](arg1, arg2);
}

export function DeleteAppel(arg1) {
  return window['go']['main']['App']['DeleteAppel'](arg1);
}

export function DeleteCHSLD(arg1) {
  return window['go']['main']['App']['DeleteCHSLD'](arg1);
}

export function DeleteCim11Code(arg1) {
  return window['go']['main']['App']['DeleteCim11Code'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteDepense(arg1) {
  return window['go']['main']['App']['DeleteDepense'](arg1);
}

export function DeleteExcelFile(arg1) {
  return window['go']['main']['App']['DeleteExcelFile'](arg1);
}

export function DeleteIntervenant(arg1) {
  return window['go']['main']['App']['DeleteIntervenant'](arg1);
}

export function DeleteMedecin(arg1) {
  return window['go']['main']['App']['DeleteMedecin'](arg1);
}

export function DeleteNotaire(arg1) {
  return window['go']['main']['App']['DeleteNotaire'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteOrganisation(arg1) {
  return window['go']['main']['App']['DeleteOrganisation'](arg1);
}

export function DeletePharmacie(arg1) {
  return window['go']['main']['App']['DeletePharmacie'](arg1);
}

export function DeleteRefListe(arg1) {
  return window['go']['main']['App']['DeleteRefListe'](arg1);
}

export function DeleteResidence(arg1) {
  return window['go']['main']['App']['DeleteResidence'](arg1);
}

export function DeleteRevenu(arg1) {
  return window['go']['main']['App']['DeleteRevenu'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function DetectLeopardKey() {
  return window['go']['main']['App']['DetectLeopardKey']();
}

export function DownloadOfficialForm(arg1) {
  return window['go']['main']['App']['DownloadOfficialForm'](arg1);
}

export function EnregistrerPaiement(arg1) {
  return window['go']['main']['App']['EnregistrerPaiement'](arg1);
}

export function ExportNotesToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportNotesToPDF'](arg1, arg2, arg3);
}

export function ExportToClientFolder(arg1) {
  return window['go']['main']['App']['ExportToClientFolder'](arg1);
}

export function GetAllAppels() {
  return window['go']['main']['App']['GetAllAppels']();
}

export function GetAllCHSLD() {
  return window['go']['main']['App']['GetAllCHSLD']();
}

export function GetAllContactsByClientID(arg1) {
  return window['go']['main']['App']['GetAllContactsByClientID'](arg1);
}

export function GetAllContrats(arg1, arg2) {
  return window['go']['main']['App']['GetAllContrats'](arg1, arg2);
}

export function GetAllDepenses(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllDepenses'](arg1, arg2, arg3, arg4);
}

export function GetAllFactures(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAllFactures'](arg1, arg2, arg3);
}

export function GetAllIntervenants() {
  return window['go']['main']['App']['GetAllIntervenants']();
}

export function GetAllNotaires() {
  return window['go']['main']['App']['GetAllNotaires']();
}

export function GetAllOrganisations(arg1, arg2) {
  return window['go']['main']['App']['GetAllOrganisations'](arg1, arg2);
}

export function GetAllPays() {
  return window['go']['main']['App']['GetAllPays']();
}

export function GetAllPharmacies() {
  return window['go']['main']['App']['GetAllPharmacies']();
}

export function GetAllRefCategories() {
  return window['go']['main']['App']['GetAllRefCategories']();
}

export function GetAllRevenus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllRevenus'](arg1, arg2, arg3, arg4);
}

export function GetAllServices(arg1, arg2) {
  return window['go']['main']['App']['GetAllServices'](arg1, arg2);
}

export function GetAppelByID(arg1) {
  return window['go']['main']['App']['GetAppelByID'](arg1);
}

export function GetArrondissements(arg1) {
  return window['go']['main']['App']['GetArrondissements'](arg1);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetCHSLDByID(arg1) {
  return window['go']['main']['App']['GetCHSLDByID'](arg1);
}

export function GetCHSLDByRegion(arg1) {
  return window['go']['main']['App']['GetCHSLDByRegion'](arg1);
}

export function GetCHSLDByStatut(arg1) {
  return window['go']['main']['App']['GetCHSLDByStatut'](arg1);
}

export function GetCHSLDCount() {
  return window['go']['main']['App']['GetCHSLDCount']();
}

export function GetCHSLDStats() {
  return window['go']['main']['App']['GetCHSLDStats']();
}

export function GetCim11ByCode(arg1) {
  return window['go']['main']['App']['GetCim11ByCode'](arg1);
}

export function GetCim11Chapitres() {
  return window['go']['main']['App']['GetCim11Chapitres']();
}

export function GetCim11DetailOMS(arg1) {
  return window['go']['main']['App']['GetCim11DetailOMS'](arg1);
}

export function GetCim11Enfants(arg1) {
  return window['go']['main']['App']['GetCim11Enfants'](arg1);
}

export function GetCim11Page(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetCim11Page'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCim11SyncMeta() {
  return window['go']['main']['App']['GetCim11SyncMeta']();
}

export function GetClientByID(arg1) {
  return window['go']['main']['App']['GetClientByID'](arg1);
}

export function GetClientFolderInfo(arg1) {
  return window['go']['main']['App']['GetClientFolderInfo'](arg1);
}

export function GetClientFolderStructure(arg1) {
  return window['go']['main']['App']['GetClientFolderStructure'](arg1);
}

export function GetClientNotes(arg1) {
  return window['go']['main']['App']['GetClientNotes'](arg1);
}

export function GetClientStoragePath(arg1, arg2) {
  return window['go']['main']['App']['GetClientStoragePath'](arg1, arg2);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetClientsByNotaire(arg1) {
  return window['go']['main']['App']['GetClientsByNotaire'](arg1);
}

export function GetClientsForPharmacie(arg1) {
  return window['go']['main']['App']['GetClientsForPharmacie'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetContratByID(arg1) {
  return window['go']['main']['App']['GetContratByID'](arg1);
}

export function GetCurrentUserProfile() {
  return window['go']['main']['App']['GetCurrentUserProfile']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDetailedFolderStructure(arg1) {
  return window['go']['main']['App']['GetDetailedFolderStructure'](arg1);
}

export function GetExcelFileInfo(arg1) {
  return window['go']['main']['App']['GetExcelFileInfo'](arg1);
}

export function GetFactureByID(arg1) {
  return window['go']['main']['App']['GetFactureByID'](arg1);
}

export function GetIntervenantByID(arg1) {
  return window['go']['main']['App']['GetIntervenantByID'](arg1);
}

export function GetMedecinByID(arg1) {
  return window['go']['main']['App']['GetMedecinByID'](arg1);
}

export function GetMedecinByLicence(arg1) {
  return window['go']['main']['App']['GetMedecinByLicence'](arg1);
}

export function GetMedecinClients(arg1) {
  return window['go']['main']['App']['GetMedecinClients'](arg1);
}

export function GetMedecinClientsCount(arg1) {
  return window['go']['main']['App']['GetMedecinClientsCount'](arg1);
}

export function GetMedecins() {
  return window['go']['main']['App']['GetMedecins']();
}

export function GetMunicipalities() {
  return window['go']['main']['App']['GetMunicipalities']();
}

export function GetMunicipalityByID(arg1) {
  return window['go']['main']['App']['GetMunicipalityByID'](arg1);
}

export function GetMunicipalityByName(arg1) {
  return window['go']['main']['App']['GetMunicipalityByName'](arg1);
}

export function GetNotaireByID(arg1) {
  return window['go']['main']['App']['GetNotaireByID'](arg1);
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetOrganisationByID(arg1) {
  return window['go']['main']['App']['GetOrganisationByID'](arg1);
}

export function GetOrganisationsListItems() {
  return window['go']['main']['App']['GetOrganisationsListItems']();
}

export function GetParametresFinance() {
  return window['go']['main']['App']['GetParametresFinance']();
}

export function GetPayeursByClient(arg1) {
  return window['go']['main']['App']['GetPayeursByClient'](arg1);
}

export function GetPaysByAlpha2(arg1) {
  return window['go']['main']['App']['GetPaysByAlpha2'](arg1);
}

export function GetPaysByAlpha3(arg1) {
  return window['go']['main']['App']['GetPaysByAlpha3'](arg1);
}

export function GetPaysByID(arg1) {
  return window['go']['main']['App']['GetPaysByID'](arg1);
}

export function GetPaysCount() {
  return window['go']['main']['App']['GetPaysCount']();
}

export function GetPaysForSelect() {
  return window['go']['main']['App']['GetPaysForSelect']();
}

export function GetPharmacieByID(arg1) {
  return window['go']['main']['App']['GetPharmacieByID'](arg1);
}

export function GetPharmacieForClient(arg1) {
  return window['go']['main']['App']['GetPharmacieForClient'](arg1);
}

export function GetPlansByClient(arg1) {
  return window['go']['main']['App']['GetPlansByClient'](arg1);
}

export function GetRapportFiscalAnnuel(arg1) {
  return window['go']['main']['App']['GetRapportFiscalAnnuel'](arg1);
}

export function GetRefListeByCategorie(arg1) {
  return window['go']['main']['App']['GetRefListeByCategorie'](arg1);
}

export function GetRefListeByID(arg1) {
  return window['go']['main']['App']['GetRefListeByID'](arg1);
}

export function GetRentabiliteParClient(arg1) {
  return window['go']['main']['App']['GetRentabiliteParClient'](arg1);
}

export function GetResidenceByID(arg1) {
  return window['go']['main']['App']['GetResidenceByID'](arg1);
}

export function GetResidenceForDetails(arg1, arg2) {
  return window['go']['main']['App']['GetResidenceForDetails'](arg1, arg2);
}

export function GetResidences() {
  return window['go']['main']['App']['GetResidences']();
}

export function GetRevenusByClient(arg1) {
  return window['go']['main']['App']['GetRevenusByClient'](arg1);
}

export function GetServiceByID(arg1) {
  return window['go']['main']['App']['GetServiceByID'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatsAppels() {
  return window['go']['main']['App']['GetStatsAppels']();
}

export function GetStatsMensuelles(arg1, arg2) {
  return window['go']['main']['App']['GetStatsMensuelles'](arg1, arg2);
}

export function GetUserCount() {
  return window['go']['main']['App']['GetUserCount']();
}

export function ImportArrondissementsCSV(arg1) {
  return window['go']['main']['App']['ImportArrondissementsCSV'](arg1);
}

export function ImportCim11() {
  return window['go']['main']['App']['ImportCim11']();
}

export function ImportIntervenants(arg1) {
  return window['go']['main']['App']['ImportIntervenants'](arg1);
}

export function ImportMedecins(arg1) {
  return window['go']['main']['App']['ImportMedecins'](arg1);
}

export function ImportMedecinsWithUpdate(arg1) {
  return window['go']['main']['App']['ImportMedecinsWithUpdate'](arg1);
}

export function ImportMunicipalitesCSV(arg1) {
  return window['go']['main']['App']['ImportMunicipalitesCSV'](arg1);
}

export function ImportNotaires(arg1) {
  return window['go']['main']['App']['ImportNotaires'](arg1);
}

export function ImportNotairesWithUpdate(arg1) {
  return window['go']['main']['App']['ImportNotairesWithUpdate'](arg1);
}

export function ImportPharmacies(arg1) {
  return window['go']['main']['App']['ImportPharmacies'](arg1);
}

export function InsertResidence(arg1) {
  return window['go']['main']['App']['InsertResidence'](arg1);
}

export function ListClientFolders() {
  return window['go']['main']['App']['ListClientFolders']();
}

export function ListExcelFiles(arg1) {
  return window['go']['main']['App']['ListExcelFiles'](arg1);
}

export function LockNote(arg1) {
  return window['go']['main']['App']['LockNote'](arg1);
}

export function LockPlan(arg1, arg2) {
  return window['go']['main']['App']['LockPlan'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenClientFolder(arg1) {
  return window['go']['main']['App']['OpenClientFolder'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenMainClientsFolder() {
  return window['go']['main']['App']['OpenMainClientsFolder']();
}

export function OuvrirDialogCSVRefListes() {
  return window['go']['main']['App']['OuvrirDialogCSVRefListes']();
}

export function RenameClientFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameClientFolder'](arg1, arg2);
}

export function RepairClientFolderStructure(arg1) {
  return window['go']['main']['App']['RepairClientFolderStructure'](arg1);
}

export function ResoudrePayeur(arg1) {
  return window['go']['main']['App']['ResoudrePayeur'](arg1);
}

export function SaveExcelFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExcelFile'](arg1, arg2);
}

export function SaveIntervenant(arg1) {
  return window['go']['main']['App']['SaveIntervenant'](arg1);
}

export function SavePDFToClientFolder(arg1) {
  return window['go']['main']['App']['SavePDFToClientFolder'](arg1);
}

export function SaveParametresFinance(arg1) {
  return window['go']['main']['App']['SaveParametresFinance'](arg1);
}

export function SavePharmacie(arg1) {
  return window['go']['main']['App']['SavePharmacie'](arg1);
}

export function SearchCHSLD(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCHSLD'](arg1, arg2, arg3);
}

export function SearchCim11(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCim11'](arg1, arg2, arg3);
}

export function SearchMedecins(arg1) {
  return window['go']['main']['App']['SearchMedecins'](arg1);
}

export function SearchPays(arg1) {
  return window['go']['main']['App']['SearchPays'](arg1);
}

export function SearchResidences(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchResidences'](arg1, arg2, arg3);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectExcelFileForClients() {
  return window['go']['main']['App']['SelectExcelFileForClients']();
}

export function SelectExcelFileForIntervenants() {
  return window['go']['main']['App']['SelectExcelFileForIntervenants']();
}

export function SelectExcelFileForMedecins() {
  return window['go']['main']['App']['SelectExcelFileForMedecins']();
}

export function SelectExcelFileForRPA() {
  return window['go']['main']['App']['SelectExcelFileForRPA']();
}

export function SetCurrentUser(arg1) {
  return window['go']['main']['App']['SetCurrentUser'](arg1);
}

export function SignerContrat(arg1, arg2) {
  return window['go']['main']['App']['SignerContrat'](arg1, arg2);
}

export function StartUsbListener(arg1) {
  return window['go']['main']['App']['StartUsbListener'](arg1);
}

export function SyncCHSLDFromMSSS() {
  return window['go']['main']['App']['SyncCHSLDFromMSSS']();
}

export function SyncRPA() {
  return window['go']['main']['App']['SyncRPA']();
}

export function UpdateAppel(arg1, arg2) {
  return window['go']['main']['App']['UpdateAppel'](arg1, arg2);
}

export function UpdateCHSLD(arg1) {
  return window['go']['main']['App']['UpdateCHSLD'](arg1);
}

export function UpdateCim11Code(arg1) {
  return window['go']['main']['App']['UpdateCim11Code'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateContact(arg1) {
  return window['go']['main']['App']['UpdateContact'](arg1);
}

export function UpdateContrat(arg1) {
  return window['go']['main']['App']['UpdateContrat'](arg1);
}

export function UpdateDepense(arg1) {
  return window['go']['main']['App']['UpdateDepense'](arg1);
}

export function UpdateFactureStatut(arg1, arg2) {
  return window['go']['main']['App']['UpdateFactureStatut'](arg1, arg2);
}

export function UpdateMedecin(arg1) {
  return window['go']['main']['App']['UpdateMedecin'](arg1);
}

export function UpdateNotaire(arg1) {
  return window['go']['main']['App']['UpdateNotaire'](arg1);
}

export function UpdateNoteDraft(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteDraft'](arg1, arg2);
}

export function UpdateOrganisation(arg1) {
  return window['go']['main']['App']['UpdateOrganisation'](arg1);
}

export function UpdatePlan(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlan'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateRefListe(arg1, arg2) {
  return window['go']['main']['App']['UpdateRefListe'](arg1, arg2);
}

export function UpdateRefListeOrdre(arg1, arg2) {
  return window['go']['main']['App']['UpdateRefListeOrdre'](arg1, arg2);
}

export function UpdateResidence(arg1) {
  return window['go']['main']['App']['UpdateResidence'](arg1);
}

export function UpdateRevenu(arg1) {
  return window['go']['main']['App']['UpdateRevenu'](arg1);
}

export function UpdateService(arg1) {
  return window['go']['main']['App']['UpdateService'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateExcelFile(arg1) {
  return window['go']['main']['App']['ValidateExcelFile'](arg1);
}

export function VerifierFacturesEnRetard() {
  return window['go']['main']['App']['VerifierFacturesEnRetard']();
}
