// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {database} from '../models';

export function ArchiveNotaire(arg1:number):Promise<void>;

export function ChangePassword(arg1:models.ChangePasswordRequest):Promise<void>;

export function ClientFolderExists(arg1:string):Promise<boolean>;

export function CreateCHSLD(arg1:models.CHSLD):Promise<void>;

export function CreateClient(arg1:models.CreateClientRequest):Promise<number>;

export function CreateClientFolderStructure(arg1:Record<string, any>):Promise<main.ClientFolderResult>;

export function CreateContact(arg1:models.CreateContactRequest):Promise<number>;

export function CreateFirstUser(arg1:main.CreateFirstUserRequest):Promise<void>;

export function CreateMedecin(arg1:models.CreateMedecinRequest):Promise<number>;

export function CreateNotaire(arg1:models.CreateNotaireRequest):Promise<number>;

export function CreateNote(arg1:models.CreateNoteRequest):Promise<number>;

export function CreateSubfolder(arg1:string,arg2:string):Promise<main.ClientFolderResult>;

export function DeleteCHSLD(arg1:number):Promise<void>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteContact(arg1:number):Promise<void>;

export function DeleteExcelFile(arg1:string):Promise<void>;

export function DeleteMedecin(arg1:number):Promise<void>;

export function DeleteNotaire(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteResidence(arg1:number):Promise<void>;

export function ExportToClientFolder(arg1:Record<string, any>):Promise<main.ClientFolderResult>;

export function GetAllCHSLD():Promise<Array<models.CHSLD>>;

export function GetAllContactsByClientID(arg1:number):Promise<Array<models.Contact>>;

export function GetAllNotaires():Promise<Array<models.Notaire>>;

export function GetBasePath():Promise<string>;

export function GetCHSLDByID(arg1:number):Promise<models.CHSLD>;

export function GetCHSLDByRegion(arg1:string):Promise<Array<models.CHSLD>>;

export function GetCHSLDByStatut(arg1:string):Promise<Array<models.CHSLD>>;

export function GetCHSLDStats():Promise<Record<string, any>>;

export function GetClientByID(arg1:number):Promise<models.Client>;

export function GetClientFolderInfo(arg1:string):Promise<main.ClientFolderInfo>;

export function GetClientFolderStructure(arg1:string):Promise<Record<string, any>>;

export function GetClientNotes(arg1:number):Promise<Array<models.NoteListItem>>;

export function GetClientNotesFiltered(arg1:models.NotesFilter):Promise<Array<models.NoteListItem>>;

export function GetClients():Promise<Array<models.Client>>;

export function GetClientsByNotaire(arg1:number):Promise<Array<models.Client>>;

export function GetContacts():Promise<Array<models.Contact>>;

export function GetCurrentUserProfile():Promise<models.User>;

export function GetDetailedFolderStructure(arg1:string):Promise<Record<string, any>>;

export function GetExcelFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetMedecinByID(arg1:number):Promise<models.Medecin>;

export function GetMedecinClients(arg1:string):Promise<Array<models.Client>>;

export function GetMedecinClientsCount(arg1:string):Promise<number>;

export function GetMedecins():Promise<Array<models.Medecin>>;

export function GetNotaireByID(arg1:number):Promise<models.Notaire>;

export function GetNoteByID(arg1:number):Promise<models.Note>;

export function GetNotesStats(arg1:number):Promise<Record<string, any>>;

export function GetResidenceByID(arg1:number):Promise<models.Residence>;

export function GetResidenceForDetails(arg1:string,arg2:boolean):Promise<models.Residence>;

export function GetResidences():Promise<Array<models.Residence>>;

export function GetSettings():Promise<models.UserSettings>;

export function GetUserCount():Promise<number>;

export function ImportMedecins(arg1:string):Promise<string>;

export function ImportMedecinsWithUpdate(arg1:string):Promise<database.ImportStats>;

export function InsertResidence(arg1:models.Residence):Promise<void>;

export function ListClientFolders():Promise<Array<string>>;

export function ListExcelFiles(arg1:main.ExcelFileType):Promise<Array<Record<string, any>>>;

export function LockNote(arg1:number):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function OpenClientFolder(arg1:string):Promise<main.ClientFolderResult>;

export function OpenFolder(arg1:string):Promise<main.ClientFolderResult>;

export function OpenMainClientsFolder():Promise<main.ClientFolderResult>;

export function RenameClientFolder(arg1:string,arg2:string):Promise<main.ClientFolderResult>;

export function RepairClientFolderStructure(arg1:string):Promise<Record<string, any>>;

export function SaveExcelFile(arg1:string,arg2:main.ExcelFileType):Promise<string>;

export function SearchCHSLD(arg1:string,arg2:string,arg3:string):Promise<Array<models.CHSLD>>;

export function SearchMedecins(arg1:string):Promise<Array<models.Medecin>>;

export function SearchResidences(arg1:string,arg2:string,arg3:string):Promise<Array<models.Residence>>;

export function SelectExcelFile():Promise<string>;

export function SelectExcelFileForClients():Promise<string>;

export function SelectExcelFileForIntervenants():Promise<string>;

export function SelectExcelFileForMedecins():Promise<string>;

export function SelectExcelFileForRPA():Promise<string>;

export function SyncRPA():Promise<Record<string, any>>;

export function UpdateCHSLD(arg1:models.CHSLD):Promise<void>;

export function UpdateClient(arg1:models.UpdateClientRequest):Promise<void>;

export function UpdateContact(arg1:models.UpdateContactRequest):Promise<void>;

export function UpdateMedecin(arg1:models.UpdateMedecinRequest):Promise<void>;

export function UpdateNotaire(arg1:models.Notaire):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;

export function UpdateProfile(arg1:models.UpdateProfileRequest):Promise<void>;

export function UpdateResidence(arg1:models.Residence):Promise<void>;

export function UpdateSettings(arg1:models.UpdateSettingsRequest):Promise<void>;

export function ValidateExcelFile(arg1:string):Promise<void>;
