// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function ClientFolderExists(arg1) {
  return window['go']['main']['App']['ClientFolderExists'](arg1);
}

export function CreateCHSLD(arg1) {
  return window['go']['main']['App']['CreateCHSLD'](arg1);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateClientFolderStructure(arg1) {
  return window['go']['main']['App']['CreateClientFolderStructure'](arg1);
}

export function CreateContact(arg1) {
  return window['go']['main']['App']['CreateContact'](arg1);
}

export function CreateFirstUser(arg1) {
  return window['go']['main']['App']['CreateFirstUser'](arg1);
}

export function CreateMedecin(arg1) {
  return window['go']['main']['App']['CreateMedecin'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteCHSLD(arg1) {
  return window['go']['main']['App']['DeleteCHSLD'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteExcelFile(arg1) {
  return window['go']['main']['App']['DeleteExcelFile'](arg1);
}

export function DeleteMedecin(arg1) {
  return window['go']['main']['App']['DeleteMedecin'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteResidence(arg1) {
  return window['go']['main']['App']['DeleteResidence'](arg1);
}

export function ExportToClientFolder(arg1) {
  return window['go']['main']['App']['ExportToClientFolder'](arg1);
}

export function GetAllCHSLD() {
  return window['go']['main']['App']['GetAllCHSLD']();
}

export function GetAllContactsByClientID(arg1) {
  return window['go']['main']['App']['GetAllContactsByClientID'](arg1);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetCHSLDByID(arg1) {
  return window['go']['main']['App']['GetCHSLDByID'](arg1);
}

export function GetCHSLDByRegion(arg1) {
  return window['go']['main']['App']['GetCHSLDByRegion'](arg1);
}

export function GetCHSLDByStatut(arg1) {
  return window['go']['main']['App']['GetCHSLDByStatut'](arg1);
}

export function GetCHSLDStats() {
  return window['go']['main']['App']['GetCHSLDStats']();
}

export function GetClientByID(arg1) {
  return window['go']['main']['App']['GetClientByID'](arg1);
}

export function GetClientFolderInfo(arg1) {
  return window['go']['main']['App']['GetClientFolderInfo'](arg1);
}

export function GetClientNotes(arg1) {
  return window['go']['main']['App']['GetClientNotes'](arg1);
}

export function GetClientNotesFiltered(arg1) {
  return window['go']['main']['App']['GetClientNotesFiltered'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetCurrentUserProfile() {
  return window['go']['main']['App']['GetCurrentUserProfile']();
}

export function GetExcelFileInfo(arg1) {
  return window['go']['main']['App']['GetExcelFileInfo'](arg1);
}

export function GetMedecinByID(arg1) {
  return window['go']['main']['App']['GetMedecinByID'](arg1);
}

export function GetMedecins() {
  return window['go']['main']['App']['GetMedecins']();
}

export function GetNoteByID(arg1) {
  return window['go']['main']['App']['GetNoteByID'](arg1);
}

export function GetNotesStats(arg1) {
  return window['go']['main']['App']['GetNotesStats'](arg1);
}

export function GetResidenceByID(arg1) {
  return window['go']['main']['App']['GetResidenceByID'](arg1);
}

export function GetResidenceForDetails(arg1, arg2) {
  return window['go']['main']['App']['GetResidenceForDetails'](arg1, arg2);
}

export function GetResidences() {
  return window['go']['main']['App']['GetResidences']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUserCount() {
  return window['go']['main']['App']['GetUserCount']();
}

export function ImportMedecins(arg1) {
  return window['go']['main']['App']['ImportMedecins'](arg1);
}

export function ImportMedecinsWithUpdate(arg1) {
  return window['go']['main']['App']['ImportMedecinsWithUpdate'](arg1);
}

export function InsertResidence(arg1) {
  return window['go']['main']['App']['InsertResidence'](arg1);
}

export function ListClientFolders() {
  return window['go']['main']['App']['ListClientFolders']();
}

export function ListExcelFiles(arg1) {
  return window['go']['main']['App']['ListExcelFiles'](arg1);
}

export function LockNote(arg1) {
  return window['go']['main']['App']['LockNote'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenClientFolder(arg1) {
  return window['go']['main']['App']['OpenClientFolder'](arg1);
}

export function OpenMainClientsFolder() {
  return window['go']['main']['App']['OpenMainClientsFolder']();
}

export function RenameClientFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameClientFolder'](arg1, arg2);
}

export function SaveExcelFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExcelFile'](arg1, arg2);
}

export function SearchCHSLD(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCHSLD'](arg1, arg2, arg3);
}

export function SearchMedecins(arg1) {
  return window['go']['main']['App']['SearchMedecins'](arg1);
}

export function SearchResidences(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchResidences'](arg1, arg2, arg3);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectExcelFileForClients() {
  return window['go']['main']['App']['SelectExcelFileForClients']();
}

export function SelectExcelFileForIntervenants() {
  return window['go']['main']['App']['SelectExcelFileForIntervenants']();
}

export function SelectExcelFileForMedecins() {
  return window['go']['main']['App']['SelectExcelFileForMedecins']();
}

export function SelectExcelFileForRPA() {
  return window['go']['main']['App']['SelectExcelFileForRPA']();
}

export function SyncRPA() {
  return window['go']['main']['App']['SyncRPA']();
}

export function UpdateCHSLD(arg1) {
  return window['go']['main']['App']['UpdateCHSLD'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateContact(arg1) {
  return window['go']['main']['App']['UpdateContact'](arg1);
}

export function UpdateMedecin(arg1) {
  return window['go']['main']['App']['UpdateMedecin'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateResidence(arg1) {
  return window['go']['main']['App']['UpdateResidence'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateExcelFile(arg1) {
  return window['go']['main']['App']['ValidateExcelFile'](arg1);
}
