// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvaluationV2(arg1) {
  return window['go']['main']['EvalHandler']['CreateEvaluationV2'](arg1);
}

export function DeleteDefinition(arg1) {
  return window['go']['main']['EvalHandler']['DeleteDefinition'](arg1);
}

export function DeleteEvaluationV2(arg1) {
  return window['go']['main']['EvalHandler']['DeleteEvaluationV2'](arg1);
}

export function GetClientEvaluationsV2(arg1) {
  return window['go']['main']['EvalHandler']['GetClientEvaluationsV2'](arg1);
}

export function GetDefinitions() {
  return window['go']['main']['EvalHandler']['GetDefinitions']();
}

export function GetEvaluationByID(arg1) {
  return window['go']['main']['EvalHandler']['GetEvaluationByID'](arg1);
}

export function SaveDefinition(arg1) {
  return window['go']['main']['EvalHandler']['SaveDefinition'](arg1);
}

export function SignerEvaluation(arg1, arg2) {
  return window['go']['main']['EvalHandler']['SignerEvaluation'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['main']['EvalHandler']['Startup'](arg1);
}

export function UpdateEvaluationV2(arg1, arg2) {
  return window['go']['main']['EvalHandler']['UpdateEvaluationV2'](arg1, arg2);
}
