// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateEvaluationV2(arg1:models.EvaluationV2):Promise<number>;

export function DeleteDefinition(arg1:string):Promise<void>;

export function DeleteEvaluationV2(arg1:number):Promise<void>;

export function GetClientEvaluationsV2(arg1:number):Promise<Array<models.EvaluationV2>>;

export function GetDefinitions():Promise<Array<models.EvaluationDefinition>>;

export function GetEvaluationByID(arg1:number):Promise<models.EvaluationV2>;

export function SaveDefinition(arg1:models.EvaluationDefinition):Promise<void>;

export function SignerEvaluation(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateEvaluationV2(arg1:number,arg2:string):Promise<void>;
