// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvaluation(arg1) {
  return window['go']['main']['EvalHandler']['CreateEvaluation'](arg1);
}

export function DeleteEvaluation(arg1) {
  return window['go']['main']['EvalHandler']['DeleteEvaluation'](arg1);
}

export function GetEvaluationByID(arg1) {
  return window['go']['main']['EvalHandler']['GetEvaluationByID'](arg1);
}

export function GetEvaluationsByClient(arg1) {
  return window['go']['main']['EvalHandler']['GetEvaluationsByClient'](arg1);
}

export function LockEvaluation(arg1, arg2) {
  return window['go']['main']['EvalHandler']['LockEvaluation'](arg1, arg2);
}

export function SignerEvaluation(arg1, arg2) {
  return window['go']['main']['EvalHandler']['SignerEvaluation'](arg1, arg2);
}
