// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateEvaluation(arg1:models.CreateEvaluationRequest):Promise<number>;

export function DeleteEvaluation(arg1:number):Promise<void>;

export function GetEvaluationByID(arg1:number):Promise<models.EvaluationSocialeDetail>;

export function GetEvaluationsByClient(arg1:number):Promise<Array<models.EvaluationSocialeDetail>>;

export function LockEvaluation(arg1:number,arg2:string):Promise<void>;

export function SignerEvaluation(arg1:number,arg2:string):Promise<void>;
